### ISSUE TITLE
AliseB - Defect: string input for slot number accepted and creates infinite loop

### ISSUE THREAD

**Issue by AliseB** [CodeDeckClub/Tic-Tac-Toe-Game-Java#1]
String input for slot number accepted and creates infinite loop

Steps to reproduce:
1. start game (run program)
2. enter String when prompted for slot number
3. infinite loop begins

Expected behavior: 
should result in an error message of invalid input
 
Actual behavior:
input was accepted

Possible fix:
verify that input is numerical

**Comment by CodeDeckClub** [comment]
Resolved:
Yes
Implemented:
```
while(!input.hasNextInt()){
                input.next();
                System.out.println("Invalid input; re-enter slot number:");
            }
```

**Comment by kevin-he-01** [comment]
This should be reopened.
This issue can be reproduced again!
The string is not accepted and there's infinite loop spamming information onto the terminal saying invalid input accepted because when an InputMismatchException is thrown the scanner **DOES NOT**
skip those characters so they are read again and again.

> When a scanner throws an `InputMismatchException`, the scanner will not pass the token that caused the exception, so that it may be retrieved or skipped via some other method.

as written in the JavaDoc of `java.util.Scanner`
If there's no exception thrown the `nextInt()` method automatically skips the integer input so it won't be read again.
